- name: Print a parameter
  hosts: localhost # to avoid mention -e password &user 
  connection: local
  tasks:
    - name: Print a Parameter
      ansible.builtin.debug:
        msg: Parameter - {{ lookup('aws_ssm', 'test.test', region='us-east-2' ) }}
  
